### PR TITLE
Json rendering issues#97

### PR DESCRIPTION
**Pull request by sgrg1**
fix issue with JSON file and displaying notes correctly.

### CODE REVIEW

**Comment by martypowell** [comment]
@sgrg1 @tmccoy529 I think maybe this was already resolved? Which of the three items in #97 does this address?

- "Trash and Recycling" breaks the app
- "Roads and Sidewalks > Icy Conditions" does not render note as expected
- "Pets and Animals > Other" does not render note as expected

**Comment by martypowell** [comment]
i think this overwrites a previous enhancement we put in for @danfox01 but doesn't account for a third scenario that we didn't consider. will follow up wiht him.

**Comment by tmccoy529** [comment]
Yeah this addresses if the form is not disabled but still displays a note field. I believe the previous changes handled no notes or if form is disabled with a note.

**Comment by martypowell** [comment]
@tmccoy529 @sgrg1 think Subcategory warnings #121 will handle this, i didn't mean to step on toes here, it was poor communcation, and something that was overlooked. This pr would overwrite features that are still desired. #121 keeps the features and adds to it. See the pr for actual details.

**Pull request closed without merging**
