### PR TITLE
Website other issues

### PR DESCRIPTION
**Pull request by martypowell**
Addresses #74 

- Only show alerts when the form is disabled on the initial panel
- Show alerts when not disabled on the provide details panel above the description field

### CODE REVIEW

**Comment by martypowell** [comment]
keeping this open for now.

**Comment by martypowell** [comment]
> This goes against my better judgement as I feel this is too much of a change to previously working code this close to a go live but the code change adds enough value to risk introducing new bugs. In the future though changes such as these should wait until after we are in production and more time to evaluate potential consequences.

@tmccoy529 i think we should walk through these changes in person tomorrow before merging.

This pr also needs to be verified in IE before merging in regards to the subcategory logic.

**Comment by martypowell** [comment]
Closing this pull request as @danfox01 said we can address this [post-launch](https://github.com/baltimorecounty/react-baltcogo/labels/post-launch).

Two issues were created to track the work as discovered in #86 

- Bug - #90 - Notes should be conditionally based on whether the form is disabled
- Enhancement - #91 - Notes should be conditionally based on whether the form is disabled

Let's discuss these issues in the next stand up, to ensure we will have to resolve these issues post launch. In the case that we don't we should consider integrating these changes prelaunch.

FYI @danfox01 @tmccoy529 @sgrg1

**Comment by martypowell** [comment]
Let's avoid deleting this branch so it can be used as a point of reference in the future.

**Comment by tmccoy529** [comment]
Because of Bug #97 that was just put out this, branch will not longer be waitlisted and instead merged to handle this error.

**Pull request merged**
